# Generated by Django 3.0.6 on 2021-03-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_auto_20210315_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='input_file',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='output_file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
