# Generated by Django 3.0.6 on 2021-05-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0003_auto_20210315_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='last_time',
            field=models.DateTimeField(null=True),
        ),
    ]
