# Generated by Django 3.0.6 on 2021-05-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0004_projects_last_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='last_time',
            field=models.TextField(null=True),
        ),
    ]
